strictness: high
test-warnings: true
doc-warnings: true
autodetect: true
max-line-length: 120

pycodestyle:
  full: true

pydocstyle:
  disable: 
  - D203
  - D204

pylint:
  run: false

ignore-paths:
- docs
- __pycache__
- keys
- .vscode
- qtasks/gui/assets/resources.py
- qtasks/gui/ui.py

ignore-patterns:
- __init__.py
- main.py